version: "3"

services:
  bot:
    build: .
    volumes:
      - ./news:/app/news
      - ./logs:/app/logs
    command: python bot.py
    restart: unless-stopped
    environment:
      - TZ=Asia/Dhaka

  gui:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./news:/app/news
    depends_on:
      - bot
    restart: unless-stopped
    environment:
      - TZ=Asia/Dhaka

volumes:
  news:
